### ISSUE TITLE
Pool requires all endpoints to be up

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-sdk-go#358]
I tried to start S3 gateway with pool of 2 nodes, where one node is down.
```yaml
peers:                                                                                                                                                                                              
  0:                                                                                                                                                                                                
    address: s01.neofs.devenv:8080 # <- This node is down                                                                                                            
  1:      
    address: s02.neofs.devenv:8080
```

S3 gateway didn't start. Don't think it is expected behavior for the pool during initialization.

```
fatal   s3-gw/app.go:271        failed to dial connection pool  {"error": "client dial: open gRPC connection: gRPC dial: context deadline exceeded"}
main.getPool
        github.com/nspcc-dev/neofs-s3-gw/cmd/s3-gw/app.go:271
main.newApp
        github.com/nspcc-dev/neofs-s3-gw/cmd/s3-gw/app.go:90
main.main
        github.com/nspcc-dev/neofs-s3-gw/cmd/s3-gw/main.go:15
runtime.main
        runtime/proc.go:250
```
